# Define o nome do workflow
name: Deploy to Github Pages

# Gatilhos
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

# Permissões
permissions:
  contents: read
  pages: write
  id-token: write

# Controle de concorrência
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # You can also do lsb_release -a && free -h for one line
      - name: Explorando o Runner
        run: lsb_release -a 
        
      - name: Testing  the RAM
        run: free -h 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        
      - name: Validar sintaxe do HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0

        with:
          root: dist/

      - name: Checar arquivos estáticos
        run:
          ls -R
          echo "Todos os arquivos foram carregados no Runner!"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
          

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
