name: Test Secret

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret
        run: |
          echo "A chave é: ${{ secrets.CHAVE_MESTRA }}"